# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        char_count ={}
        for char in s+t:
            char_count[char] = 0
        for char in s:
            if char not in char_count:
                char_count[char] = 1
            else:
                char_count[char] += 1
        for char in t:
            char_count[char] -= 1
            if char_count[char] < 0:
                return char

sol = Solution()
s = 'abcd'
t = 'abcde'
print(sol.findTheDifference(s, t))